apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: recommendation
spec:
  resources:
    - name: repo
      type: git
    - name: build-image
      type: image

  tasks:
    - name: build
      taskRef:
        name: rec-buildah
        kind: Task
      resources:
        inputs:
          - name: source
            resource: repo
        outputs:
          - name: image
            resource: build-image
    - name: dataset
      taskRef:
        name: rec-dataset
        kind: Task
      resources:
        inputs:
          - name: image
            resource: build-image
        outputs:
          - name: image
            resource: build-image
      runAfter:
        - build
    - name: run
      taskRef: 
        name: rec-run
        kind: Task
      resources:
        inputs:
          - name: image
            resource: build-image
      runAfter:
        - dataset
