---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/raynalee4/mlperf-training.git #https://github.com/AICoE/mlperf-training.git
    - name: revision
      value: image-classification-2
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: build-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/mlperf/image-classification:latest
---